version: "3"

env:
  UBUNTU_IMAGE: "dotfiles/ubuntu"
  LOG_DIR: "logs"

tasks:
  default:
    cmds:
      - task -l --sort none
    slient: true

  build:ubuntu:
    desc: "Build Docker image for Ubuntu"
    cmds:
      - |
        timestamp=$(date +'%Y%m%d-%H%M%S')
        echo "timestamp: ${timestamp}"
        mkdir -p {{ .LOG_DIR }}
        docker build -t {{ .UBUNTU_IMAGE }} -f ubuntu.dockerfile . --progress=plain |& tee {{ .LOG_DIR }}/docker-build-${timestamp}.log
  
  run:ubuntu:
    desc: "Run Docker container for Ubuntu"
    cmds:
      - |
        docker run -it {{ .UBUNTU_IMAGE }} bash

  run:macos:
    desc: "Build Docker image for macOS"
    cmds:
      - |
        timestamp=$(date +'%Y%m%d-%H%M%S')
        echo "timestamp: ${timestamp}"
        mkdir -p {{ .LOG_DIR }}
        docker run -it \
          --device /dev/kvm \
          -p 50922:10022 \
          -v /tmp/.X11-unix:/tmp/.X11-unix \
          -e "DISPLAY=${DISPLAY:-:0.0}" \
          -e GENERATE_UNIQUE=true \
          -e CPU='Haswell-noTSX' \
          -e CPUID_FLAGS='kvm=on,vendor=GenuineIntel,+invtsc,vmware-cpuid-freq=on' \
          -e MASTER_PLIST_URL='https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom-sonoma.plist' \
          -e SHORTNAME=tahoe \
          sickcodes/docker-osx:latest |& tee {{ .LOG_DIR }}/docker-macos-build-${timestamp}.log

