version: "3"

env:
  UBUNTU_IMAGE: "dotfiles/ubuntu"
  LOG_DIR: "logs"

tasks:
  default:
    cmds:
      - task -l --sort none
    silent: true

  build:ubuntu:
    desc: "Build Docker image for Ubuntu"
    cmds:
      - |
        timestamp=$(date +'%Y%m%d-%H%M%S')
        echo "timestamp: ${timestamp}"
        mkdir -p {{ .LOG_DIR }}
        docker build -t {{ .UBUNTU_IMAGE }} . --progress=plain |& tee {{ .LOG_DIR }}/docker-build-${timestamp}.log

  run:ubuntu:
    desc: "Run Docker container for Ubuntu"
    cmds:
      - |
        docker run -it {{ .UBUNTU_IMAGE }} bash

  run:macos:
    desc: "Build Docker image for macOS"
    cmds:
      - |
        echo "Use tart. e.g."
        echo "tart clone ghcr.io/cirruslabs/macos-sequoia-base:latest sequoia"
        echo "tart run sequoia"
