#!/usr/bin/env bash

set -eu

if ! command -v apt > /dev/null 2>&1; then
  echo "ubuntu/install - This script requires apt as package manager"
  exit 1
fi

DOTFILES_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

source "$DOTFILES_ROOT/ubuntu/apt.sh"

