require("config.options")
require("config.keymaps")
require("config.abbr")
require("config.autocmd")
require("config.filetype")
require("core.lazy")
require("config.lsp")
require("config.diagnostic")
