#!/usr/bin/env bash

set -eu

function print() {
  printf "\033[0;35m$*\033[0m"
}

function get_distribution() {
  if [[ -e /etc/debian_version || -e /etc/debian_release ]]; then
    if [[ -e /etc/lsb-release ]]; then
      echo "ubuntu"
    else
      echo "debian"
    fi
    return
  fi

  if [[ -e /etc/fedora-release ]]; then
    echo "fedora"
    return
  fi

  if [[ -e /etc/redhat-release ]]; then
    if [[ -e /etc/oracle-release ]]; then
      echo "oracle"
    else
      echo "redhat"
    fi
    return
  fi

  if [[ -e /etc/arch-release ]]; then
    echo "arch"
    return
  fi

  echo "unknown"
}

if [[ "$(uname)" == "Darwin" ]]; then
  dist="macos"
else
  dist=$(get_distribution)
fi

print "Detected OS/Distribution: $dist\n"

DOTFILES_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FIND_SEARCH_DEPTH=4

# OS-specific installation
print "OS-specific installation\n"
if [[ -f "$DOTFILES_ROOT/$dist/install" ]]; then
  bash "$DOTFILES_ROOT/$dist/install"
fi

# Create symbolic links
print "Create symbolic links\n"
bash "$DOTFILES_ROOT/scripts/link"

# Scripts with .$dist suffix
print "Run scripts with .$dist suffix\n"
files=$(find -H "$DOTFILES_ROOT" -maxdepth "$FIND_SEARCH_DEPTH" -name "*.sh.${dist}" -not -path '*.git*')
for src in $files; do
  dirname="$(dirname "$src")"
  basename="$(basename "$dirname")"
  print "Run $basename install script? [Y/n]: "
  read -r ans
  case "$ans" in
  [Nn])
    continue
    ;;
  *) ;;
  esac
  bash "$src"
done

# Scripts with .common suffix
print "Run scripts with .common suffix\n"
files=$(find -H "$DOTFILES_ROOT" -maxdepth "$FIND_SEARCH_DEPTH" -name "*.common" -not -path '*.git*')
for src in $files; do
  dirname="$(dirname "$src")"
  basename="$(basename "$dirname")"
  print "Run $basename install script? [Y/n]: "
  read -r ans
  case "$ans" in
  [Nn])
    continue
    ;;
  *) ;;
  esac
  bash "$src"
done

# Run after script
print "Run after hook scripts\n"
bash "$DOTFILES_ROOT/scripts/after"

print "Done\n"
