#!/usr/bin/env bash

# This script creates symbolic links for files ending with `.symlink`,
# then runs all `after.sh` scripts in this repository.

set -eu

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)
FIND_SEARCH_DEPTH=4
TIMESTAMP=$(date +%Y%m%d%H%M%S)

function print() {
  local fmt="$1"
  shift
  printf "\033[0;35mscripts/link: \033[0m$fmt" "$@"
}

function create_symlink() {
  local src=$1 dst=$2
  local opt="undefined"

  if [[ -L "$dst" || -e "$dst" ]] && [[ "$(readlink "$dst")" == "$src" ]]; then
    opt="skip"
  fi

  if [[ -L "$dst" || -e "$dst" ]] && [[ "$opt" == "undefined" ]]; then
    while :; do
      print "File already exists: %s\n" "$dst"
      print " [s]kip, [o]verwrite, [b]ackup?: "
      # Add '|| true' to avoid exiting with Ctrl+D
      read -r ans || true
      case "$ans" in
      oO)
        opt="overwrite"
        break
        ;;
      bB)
        opt="backup"
        break
        ;;
      sS)
        opt="skip"
        break
        ;;
      "") ;;
      *)
        echo "Invalid option: $ans"
        ;;
      esac
    done
  fi

  if [[ "$opt" == "undefined" ]]; then
    # Some after.sh require that symbolic links are properly created.
    opt="create"
    # while :; do
    #   print "Create link to \"%s\"? (Y/n)" "$dst"
    #   # Add '|| true' to avoid exiting with Ctrl+D
    #   read -r ans || true
    #
    #   case "$ans" in
    #   "" | [yY])
    #     opt="create"
    #     break
    #     ;;
    #   [nN])
    #     opt="skip"
    #     break
    #     ;;
    #   *)
    #     print "Invalid choice: '$ans'. Please enter [y]es or [n]o.\n"
    #     ;;
    #   esac
    # done
  fi

  if [[ "$opt" == "skip" ]]; then
    return
  fi

  if [[ "$opt" == "backup" ]]; then
    mv "$dst" "${dst}.bak.${TIMESTAMP}"
    print "Backed up: ${dst} -> ${dst}.bak.${TIMESTAMP}"
  fi

  if [[ "$opt" == "overwrite" ]]; then
    rm -rf "$dst"
  fi

  mkdir -p "$(dirname "$dst")"
  ln -sv "$src" "$dst"
}

# Create symbolic links
print "Create symbolic links\n"

files=$(find -H "$DOTFILES_ROOT" -maxdepth $FIND_SEARCH_DEPTH -name '*.symlink' -not -path '*.git*')
for src in $files; do
  left_trimmed=${src#"${DOTFILES_ROOT}/"}
  dst="$HOME/${left_trimmed%.symlink}"
  create_symlink "$src" "$dst"
done

print "Symbolic created (or already set).\n"

# Run after script
print "Run after hook scripts\n"

files=$(find -H "$DOTFILES_ROOT" -maxdepth $FIND_SEARCH_DEPTH -name 'after.sh' -not -path '*.git*')
for src in $files; do
  bash "$src"
done

print "After scritps ran\n"
print "Done\n"
