#!/usr/bin/env bash

FIND_SEARCH_DEPTH=4

set -e

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)
TIMESTAMP=$(date +%Y%m%d%H%M%S)

# https://github.com/holman/dotfiles/blob/master/script/bootstrap
function create_symlink() {
  local src=$1 dst=$2

  local overwrite_opt=${global_opt:-"undefined"}

  if [[ -L "$dst" || -e "$dst" ]]; then

    if [[ "$(readlink "$dst")" == "$src" ]]; then
      overwrite_opt="skip"
    fi

    if [[ "$overwrite_opt" == "undefined" ]]; then
      while :; do
        printf "File already exists: %s\n" "$dst"
        printf " [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?: "
        read -r ans
        case "$ans" in
        o)
          overwrite_opt="overwrite"
          break
          ;;
        O)
          overwrite_opt="overwrite"
          global_opt="overwrite"
          break
          ;;
        b)
          overwrite_opt="backup"
          break
          ;;
        B)
          overwrite_opt="backup"
          global_opt="backup"
          break
          ;;
        s)
          overwrite_opt="skip"
          break
          ;;
        S)
          overwrite_opt="skip"
          global_opt="skip"
          break
          ;;
        "") ;;
        *)
          echo "Invalid option: $ans"
          ;;
        esac
      done
    fi
  fi

  if [[ "$overwrite_opt" == "skip" ]]; then
    return
  fi

  if [[ "$overwrite_opt" == "backup" ]]; then
    mv "$dst" "${dst}.bak.${TIMESTAMP}"
    echo "Backed up: ${dst} -> ${dst}.bak.${TIMESTAMP}"
  fi

  if [[ "$overwrite_opt" == "overwrite" ]]; then
    rm -rf "$dst"
  fi

  mkdir -p "$(dirname "$dst")"
  ln -sv "$src" "$dst"
}

function link() {
  echo "Setting up symlinks..."

  local global_opt=""

  files=$(find -H "$DOTFILES_ROOT" -maxdepth $FIND_SEARCH_DEPTH -name '*.symlink' -not -path '*.git*')
  for src in $files; do
    left_trimmed=${src#"${DOTFILES_ROOT}/"}
    dst="$HOME/${left_trimmed%.symlink}"
    create_symlink "$src" "$dst"
  done
}

link
