on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  macOS:
    runs-on: macos-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dotfiles
        run: |
          chmod +x ./install.sh
          ./install.sh

  Ubuntu:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dotfiles
        run: |
          sudo chmod +x ./install.sh
          sudo ./install.sh
